{
	class: "icon-d-before",
	code: "&#xe683;"
}, {
	class: "icon-d-upper",
	code: "&#xe684;"
}, {
	class: "icon-d-after",
	code: "&#xe685;"
}, {
	class: "icon-d-right",
	code: "&#xe687;"
}, {
	class: "icon-d-lower",
	code: "&#xe688;"
}, {
	class: "icon-d-open",
	code: "&#xe68a;"
}, {
	class: "icon-d-packup",
	code: "&#xe68c;"
}, {
	class: "icon-arrow-lower",
	code: "&#xe68d;"
}, {
	class: "icon-arrow-upper",
	code: "&#xe68e;"
}, {
	class: "icon-d-lower-line",
	code: "&#xe69b;"
}, {
	class: "icon-d-upper-line",
	code: "&#xe69d;"
}, {
	class: "icon-d-left-line",
	code: "&#xe69e;"
}, {
	class: "icon-d-right-line",
	code: "&#xe6a0;"
}, {
	class: "icon-m-increase",
	code: "&#xe689;"
}, {
	class: "icon-m-reduce",
	code: "&#xe68b;"
}, {
	class: "icon-correct",
	code: "&#xe68f;"
}, {
	class: "icon-correct-line",
	code: "&#xe695;"
}, {
	class: "icon-error-line",
	code: "&#xe696;"
}, {
	class: "icon-correct-solid",
	code: "&#xe698;"
}, {
	class: "icon-error-solid",
	code: "&#xe69a;"
}, {
	class: "icon-m-reduce-line",
	code: "&#xe69c;"
}, {
	class: "icon-m-increase-line",
	code: "&#xe6a1;"
}, {
	class: "icon-help",
	code: "&#xe692;"
}, {
	class: "icon-tips",
	code: "&#xe694;"
}, {
	class: "icon-info",
	code: "&#xe697;"
}, {
	class: "icon-info-solid",
	code: "&#xe699;"
}, {
	class: "icon-p-enlarge",
	code: "&#xe6b0;"
}, {
	class: "icon-p-narrow",
	code: "&#xe6b1;"
}, {
	class: "icon-f-upload1",
	code: "&#xe691;"
}, {
	class: "icon-f-download1",
	code: "&#xe693;"
}, {
	class: "icon-setup",
	code: "&#xe6a3;"
}, {
	class: "icon-f-upload2",
	code: "&#xe6a4;"
}, {
	class: "icon-f-download2",
	code: "&#xe6a6;"
}, {
	class: "icon-refresh",
	code: "&#xe6a9;"
}, {
	class: "icon-gender-female",
	code: "&#xe6ab;"
}, {
	class: "icon-gender-male",
	code: "&#xe6ac;"
}, {
	class: "icon-edit",
	code: "&#xe6ad;"
}, {
	class: "icon-sort",
	code: "&#xe6ae;"
}, {
	class: "icon-more",
	code: "&#xe6af;"
}, {
	class: "icon-exit",
	code: "&#xe6b4;"
}, {
	class: "icon-close",
	code: "&#xe663;"
}, {
	class: "icon-eye-show",
	code: "&#xe6b5;"
}, {
	class: "icon-eye-hide",
	code: "&#xe6b6;"
}, {
	class: "icon-share",
	code: "&#xe6b7;"
}, {
	class: "icon-list",
	code: "&#xe6b8;"
}, {
	class: "icon-block-list",
	code: "&#xe6b9;"
}, {
	class: "icon-mail",
	code: "&#xe6bb;"
}, {
	class: "icon-screening",
	code: "&#xe6b2;"
}, {
	class: "icon-password",
	code: "&#xe690;"
}, {
	class: "icon-mobile-phone",
	code: "&#xe6a7;"
}, {
	class: "icon-account",
	code: "&#xe69f;"
}, {
	class: "icon-phone",
	code: "&#xe6ba;"
}, {
	class: "icon-address",
	code: "&#xe6a8;"
}, {
	class: "icon-scan-code",
	code: "&#xe6aa;"
}, {
	class: "icon-goods",
	code: "&#xe6bc;"
}, {
	class: "icon-shop",
	code: "&#xe6bd;"
}, {
	class: "icon-calendar",
	code: "&#xe6f5;"
}, {
	class: "icon-news",
	code: "&#xe62f;"
}, {
	class: "icon-pyq",
	code: "&#xe7be;"
}, {
	class: "icon-qq-solid",
	code: "&#xe80e;"
}, {
	class: "icon-wx-solid",
	code: "&#xe7e5;"
}, {
	class: "icon-qqkj",
	code: "&#xe80f;"
}, {
	class: "icon-v-play",
	code: "&#xe610;"
}, {
	class: "icon-v-stop",
	code: "&#xe611;"
}, {
	class: "icon-about",
	code: "&#xe62c;"
}, {
	class: "icon-warning",
	code: "&#xe617;"
}, {
	class: "icon-user",
	code: "&#xe606;"
}, {
	class: "icon-user-solid",
	code: "&#xe60e;"
}, {
	class: "icon-home",
	code: "&#xeb32;"
}, {
	class: "icon-home-solid",
	code: "&#xeb94;"
}, {
	class: "icon-wb",
	code: "&#xe7e4;"
}, {
	class: "icon-wx",
	code: "&#xe62a;"
}, {
	class: "icon-qq",
	code: "&#xe65b;"
}, {
	class: "icon-zfb",
	code: "&#xe64b;"
}, {
	class: "icon-zfb-solid",
	code: "&#xe647;"
}, {
	class: "icon-picture",
	code: "&#xe6e9;"
}, {
	class: "icon-search",
	code: "&#xe62e;"
}, {
	class: "icon-delete",
	code: "&#xe614;"
}, {
	class: "icon-Group-1",
	code: "&#xe682;"
}, {
	class: "icon-close1",
	code: "&#xe686;"
}, {
	class: "icon-star-solid",
	code: "&#xe62b;"
}, {
	class: "icon-star",
	code: "&#xe629;"
}